
library(gridExtra)
library(tidyverse)
urlhead = 'http://www.exposomex.cn:8080/'

#' @title Initialize IVFPred module
#' @description Initialize IVFPred module analysis. It can generate an R6 class object.
#' @usage InitIVF()
#' @details IVFPred module is designed to improve model efficiency in
#'          predicting pregnancy success rates in IVF-ET and screening
#'          the key influencing factors for the individual centers and
#'          patients.
#' @return An R6 class object.
#' @export
#' @examples res <- InitIVF()
#' @author Weinan Lin, Bin Wang (corresponding author)

InitIVF = function(){
  url = paste0(urlhead,'InitIVF')
  seednum = sample(1000,1)
  res = httr::POST(url,
                   body = list(seednum=seednum),
                   encode = 'json')
  results = unserialize(httr::content(res))
  return(results$eSet)
}

#' @title Load data file for IVFPred module
#' @description Load data file for IVFPred module
#' @usage LoadIVF(PID, UseExample = "default", DataPath = NULL, VocaPath = NULL)
#' @param PID chr. Program ID. It must be the same with the PID generated by IVFPred
#' @param UseExample chr. Method of uploading data. If "default",user should upload their own data files,
#'    or use "example#1" or "example#2" provided by this module.
#' @param DataPath chr. Input directory of data file, e.g. "D:/test/eg_data_IVFPred.xlsx". It should be
#'    noted that the slash symbol is "/", not "\".
#' @param VocaPath chr. Input directory of vocabulary file, e.g. "D:/test/eg_voca_IVFPred.xlsx". It should be
#'    noted that the slash symbol is "/", not "\".
#' @return An R6 class object containing the input data.
#' @export
#' @examples res <- InitIVF()
#'    res = LoadIVF(PID = res$PID, UseExample = "example#1")
#' @author Weinan Lin, Bin Wang (corresponding author)

LoadIVF =function(PID,
                  UseExample = "default",
                  DataPath = NULL,
                  VocaPath = NULL){
  url = paste0(urlhead,'LoadIVF')
  if(UseExample=="default"){
    exdata = readxl::read_excel(DataPath)
    vodata = readxl::read_excel(VocaPath)
  }else{
    exdata = NULL
    vodata = NULL}
  res = httr::POST(url,
                   body = serialize(list(PID = PID,
                                         UseExample = UseExample,
                                         Expodata = exdata,
                                         Vocadata = vodata),connection = NULL),
                   httr::content_type('application/x-rds'),
                   encode = 'raw')
  results = unserialize(httr::content(res))
  # results list
  return(results$eSet)
}

#' @title Missing data imputation for IVF-ET data
#' @description Missing data imputation.
#' @usage TransImputIVF(PID,OutPath = "default",Vars)
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param Vars Variables to be imputed. Available options include:
#'     "all.x", all exposure variables;
#'     It should be noted that there is fixed format for the entering characters
#'     separated with comma and without space, e.g., "X1,X2,X3".
#' @details
#' @return An R6 class object containing variable(s) with imputation.
#' @export
#' @examples res <- InitIVF()
#'     res1 = LoadIVF(PID = res$PID, UseExample = "example#1")
#'     res2 = TransImputIVF(PID=res$PID, Vars="all.x")
#'     FuncExit(PID = res$PID)
#' @author Weinan Lin, Bin Wang (corresponding author)

TransImputIVF =function(PID,
                     OutPath = "default",
                     Vars){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'TransImputIVF')
  res = httr::POST(url,
                   body = list(IVFPredPID=PID,
                               TransImputVars=Vars),
                   encode = 'json')
  results = unserialize(httr::content(res))

  dir.create(paste0(OutPath,'/TransImputIVF'))
  try(vroom::vroom_write(results$eSet$Expo$Data,
                         paste0(OutPath,'/TransImputIVF/Expo_Data.csv'),
                         delim = ","),silent = TRUE
  )
  try(vroom::vroom_write(results$eSet$Expo$Voca,
                         paste0(OutPath,'/TransImputIVF/Expo_Voca.csv'),
                         delim = ","),silent = TRUE
  )

  return(results$eSet)
}


#' @title Delete variables with low variance for IVF-ET data
#' @description Delete variables with low variance
#' @usage DelLowVarIVF(PID, OutPath = "default")
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @details
#' @return An R6 class object containing the variable(s) with acceptable variance.
#' @export
#' @examples res <- InitIVF()
#'     res1 = LoadIVF(PID = res$PID, UseExample = "example#1")
#'     res2 = DelLowVarIVF(PID=res$PID)
#'     FuncExit(PID = res$PID)
#' @author Weinan Lin, Bin Wang (corresponding author)

DelLowVarIVF = function(PID,
                          OutPath = "default"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'DelLowVarIVF')
  res =  httr::POST(url,
                    body = list(IVFPredPID=PID),
                    encode = 'json')
  results = unserialize(httr::content(res))

  dir.create(paste0(OutPath,'/DelLowVarIVF'))
  try(vroom::vroom_write(results$eSet$Expo$Data,
                         paste0(OutPath,'/DelLowVarIVF/Expo_Data.csv'),
                         delim = ","),silent = TRUE
  )
  try(vroom::vroom_write(results$eSet$Expo$Voca,
                         paste0(OutPath,'/DelLowVarIVF/Expo_Voca.csv'),
                         delim = ","),silent = TRUE
  )

  return(results$eSet)
}


#' @title Delete variables with missing values for IVF-ET data
#' @description Delete missing variables with low variance
#' @usage DelMissIVF(PID, OutPath = "default")
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @details
#' @return An R6 class object containing the variable(s) without missing values.
#' @export
#' @examples res <- InitIVF()
#'     res1 = LoadIVF(PID = res$PID, UseExample = "example#1")
#'     res2 = DelMissIVF(PID=res$PID)
#'     FuncExit(PID = res$PID)
#' @author Weinan Lin, Bin Wang (corresponding author)

DelMissIVF = function(PID,
                   OutPath = "default"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url =paste0(urlhead,'DelMissIVF')
  res = httr::POST(url,
                   body = list(IVFPredPID=PID),
                   encode = 'json')

  dir.create(paste0(OutPath,'/DelMissIVF'))
  try(vroom::vroom_write(results$eSet$Expo$Data,
                         paste0(OutPath,'/DelMissIVF/Expo_Data.csv'),
                         delim = ","),silent = TRUE
  )
  try(vroom::vroom_write(results$eSet$Expo$Voca,
                         paste0(OutPath,'/DelMissIVF/Expo_Voca.csv'),
                         delim = ","),silent = TRUE
  )

  results = unserialize(httr::content(res))
  return(results$eSet)
}


#' @title Transform data type for IVF-ET data
#' @description Transform data type
#' @usage TransTypeIVF(PID,OutPath = "default",Vars,To)
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param Vars Variables to be imputed. Available options include:
#'     "all.x", all exposure variables;
#'     It should be noted that there is fixed format for the entering characters
#'     separated with comma and without space, e.g., "X1,X2,X3".
#' @param To chr. Indicate the type of the chosen variables to be transformed into.
#'     Available options include "integer", "numeric", "character", "factor", "logical", and "date".
#' @details
#' @return An R6 class object containing the variable(s) after transforming data type.
#' @export
#' @examples res <- InitIVF()
#'     res1 = LoadIVF(PID = res$PID, UseExample = "example#1")
#'     res2 = TransTypeIVF(PID = res$PID, Vars = "all.x", To = "character")
#'     FuncExit(PID = res$PID)
#' @author Weinan Lin, Bin Wang (corresponding author)

TransTypeIVF = function(PID,
                     OutPath = "default",
                     Vars,
                     To){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'TransTypeIVF')
  res = httr::POST(url,
                   body = list(IVFPredPID=PID,
                               TransTypeVars=Vars,
                               TransTypeTo=To),
                   encode = 'json')

  dir.create(paste0(OutPath,'/TransTypeIVF'))
  try(vroom::vroom_write(results$eSet$Expo$Data,
                         paste0(OutPath,'/TransTypeIVF/Expo_Data.csv'),
                         delim = ","),silent = TRUE
  )
  try(vroom::vroom_write(results$eSet$Expo$Voca,
                         paste0(OutPath,'/TransTypeIVF/Expo_Voca.csv'),
                         delim = ","),silent = TRUE
  )

  results = unserialize(httr::content(res))
  return(results$eSet)
}


#' @title Classify variables into various groups for IVF-ET data
#' @description Classify variables into various groups
#' @usage TransClassIVF(PID, OutPath = "default", Vars, LevelTo)
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param Vars Variables to be imputed. Available options include:
#'     "all.x", all exposure variables;
#'     It should be noted that there is fixed format for the entering characters
#'     separated with comma and without space, e.g., "X1,X2,X3".
#' @param LevelTo The number of levels to convert variables to.
#' @details
#' @return An R6 class object containing the variable(s) after classifying data into various levels.
#' @export
#' @examples res <- InitIVF()
#'     res1 = LoadIVF(PID = res$PID, UseExample = "example#1")
#'     res2 = TransClassIVF(PID = res$PID, Vars = "X47", LevelTo = 4)
#'     FuncExit(PID = res$PID)
#' @author Weinan Lin, Bin Wang (corresponding author)

TransClassIVF = function(PID,
                      OutPath = "default",
                      Vars,
                      LevelTo){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'TransClassIVF')
  res = httr::POST(url,
                   body = list(IVFPredPID=PID,
                               TransClassVars=Vars,
                               TransClassLevelTo=LevelTo),
                   encode = 'json')

  dir.create(paste0(OutPath,'/TransClassIVF'))
  try(vroom::vroom_write(results$eSet$Expo$Data,
                         paste0(OutPath,'/TransClassIVF/Expo_Data.csv'),
                         delim = ","),silent = TRUE
  )
  try(vroom::vroom_write(results$eSet$Expo$Voca,
                         paste0(OutPath,'/TransClassIVF/Expo_Voca.csv'),
                         delim = ","),silent = TRUE
  )

  results = unserialize(httr::content(res))
  return(results$eSet)
}


#' @title Scale variables for IVF-ET data
#' @description Scale variables
#' @usage TransScaleIVF(PID,OutPath = "default", Vars, Method = "normal",Direct="positive",
#'       RangeLow="0", RangeUpper="1")
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param Vars Variables to be imputed. Available options include:
#'     "all.x", all exposure variables;
#'     It should be noted that there is fixed format for the entering characters
#'     separated with comma and without space, e.g., "X1,X2,X3".
#' @param Method chr. Scaling methods. Available options include "normal" and "range".
#' @param Direct chr. Direction to be transformed, Available options include "positive" and "negative".
#' @param RangeLow num. Lower limit for range method.
#' @param RangeUpper num. Upper limit for range method. It should be greater than the lower limit.
#' @details
#' @return An R6 class object containing the variable(s) after scaling data.
#' @export
#' @examples res <- InitIVF()
#'     res1 = LoadIVF(PID = res$PID, UseExample = "example#1")
#'     res2 = TransScaleIVF(PID = res$PID, Vars = "X55", Method = "normal")
#'     FuncExit(PID = res$PID)
#' @author Weinan Lin, Bin Wang (corresponding author)

TransScaleIVF = function(PID,
                      OutPath = "default",
                      Vars,
                      Method = "normal",
                      Direct="positive",
                      RangeLow="0",
                      RangeUpper="1"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'TransScaleIVF')
  res = httr::POST(url,
                   body = list(IVFPredPID=PID,
                               TransScaleVars=Vars,
                               TransScaleMethod=Method,
                               TransScaleDirect=Direct,
                               TransScaleRangeLow=RangeLow,
                               TransScaleRangeUpper=RangeUpper),
                   encode = 'json')
  results = unserialize(httr::content(res))

  dir.create(paste0(OutPath,'/TransScaleIVF'))
  try(vroom::vroom_write(results$eSet$Expo$Data,
                         paste0(OutPath,'/TransScaleIVF/Expo_Data.csv'),
                         delim = ","),silent = TRUE
  )
  try(vroom::vroom_write(results$eSet$Expo$Voca,
                         paste0(OutPath,'/TransScaleIVF/Expo_Voca.csv'),
                         delim = ","),silent = TRUE
  )

  return(results$eSet)
}


#' @title Transform variable distribution for IVF-ET data
#' @description Transform variable distribution
#' @usage TransDistrIVF(PID,OutPath = "default", Vars, Method)
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param Vars Variables to be imputed. Available options include:
#'     "all.x", all exposure variables;
#'     It should be noted that there is fixed format for the entering characters
#'     separated with comma and without space, e.g., "X1,X2,X3".
#' @param Method chr. Methods used for imputation. Available options include "lod" or "cart".
#'     For "lod" method, limit of detection (LOD) should be included in the "Vocabulary" file.
#' @details
#' @return An R6 class object containing the variable(s) after transforming distribution.
#' @export
#' @examples res <- InitIVF()
#'     res1 = LoadIVF(PID = res$PID, UseExample = "example#1")
#'     res2 = TransDistrIVF(PID = res$PID, Vars = "X61", Method = "log10")
#'     FuncExit(PID = res$PID)
#' @author Weinan Lin, Bin Wang (corresponding author)

TransDistrIVF = function(PID,
                      OutPath = "default",
                      Vars,
                      Method){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'TransDistrIVF')
  res = httr::POST(url,
                   body = list(IVFPredPID=PID,
                               TransDistrVars=Vars,
                               TransDistrMethod=Method),
                   encode = 'json')

  dir.create(paste0(OutPath,'/TransDistrIVF'))
  try(vroom::vroom_write(results$eSet$Expo$Data,
                         paste0(OutPath,'/TransDistrIVF/Expo_Data.csv'),
                         delim = ","),silent = TRUE
  )
  try(vroom::vroom_write(results$eSet$Expo$Voca,
                         paste0(OutPath,'/TransDistrIVF/Expo_Voca.csv'),
                         delim = ","),silent = TRUE
  )

  results = unserialize(httr::content(res))
  return(results$eSet)
}




#' @title Build predict model for IVF-ET data
#' @description Build predict model for IVF-ET data
#' @usage IVFPred(PID, OutPath = "default", AutTuneM = "random_search", AutTuneN = "5", RsmpMethod = "cv", Folds = "5", Ratio = NULL, Repeats = NULL, Learners = NULL)
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param AutTuneM chr. Method for hyper-parameter autotuning.
#'     Options include "default", "random_search", "grid_search", "nloptr"(Non-linear optimization), and "gensa"(Generalized simulated annealing).
#'     The "default" option uses the simple training method for parameter optimization of mlr3 package.
#' @param AutTuneN num. Upper limit of model tuning times. It should be more than 20 times to search the appropriate parameters,
#'     but it takes more time. In theory, more time, better training results.
#' @param RsmpMethod chr. Method for resampling. Options include "cv"(cross validation), "loo"(leave-one-out cross validation),
#'     "bootstrap"(bootstrapping), "holdout"(holdout).
#' @param Folds num. Folds for cross validation resampling method. The default value is 5.
#' @param Ratio num. Ratio for "Holdout" resampling method. The default value is 5.
#' @param Repeats num. Repeats for "Bootstrap" resampling method.
#' @param Learners chr. Learners for build IVF-ET outcome predicting model. Options include "lasso", "elastic net", "rf"(Random forest), "stacked generalization", "logistic" and "xgboost"(Xgboost).
#'     One or more arbitrary options can be selected at the same time. Note that separates different learners by "," and without space(e.g. Learners ="lasso,rf,xgboost").
#' @return An R6 class object containing the model results
#' @export
#' @examples
#'     res <- InitIVF()
#'    res1 = LoadIVF(PID = res$PID, UseExample = "example#2")
#'    res2 = TransImputIVF(PID=res$PID, Vars="all.x")
#'    res2 = DelLowVarIVF(PID=res$PID)
#'    res2 = DelMissIVF(PID=res$PID)
#'    res2 = TransTypeIVF(PID = res$PID, Vars = "Y,X85,X86,X87,X88,X89,X90,X91,X92,X93,X94,X95,X96,X97,X98",
#'                        To = "factor")
#'    res2 = TransClassIVF(PID = res$PID, Vars = "X47", LevelTo = 4)
#'    res2 = TransScaleIVF(PID = res$PID, Vars = "X55", Method = "normal")
#'    res2 = TransDistrIVF(PID = res$PID, Vars = "X61", Method = "log10")
#'    res3 = IVFPred(PID = res$PID, AutTuneM = "random_search", AutTuneN = 5,
#'                   RsmpMethod = "cv", Folds = 5,
#'                   Learners = "logistic,rf,xgboost")
#'    FuncExit(PID = res$PID)
#' @author Weinan Lin, Bin Wang (corresponding author)

IVFPred = function(PID,
                   OutPath = "default",
                   AutTuneM = "random_search",
                   AutTuneN = "5",
                   RsmpMethod = "cv",
                   Folds = "5",
                   Ratio = NULL,
                   Repeats = NULL,
                   Learners = NULL){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  url = paste0(urlhead,'IVFPred')

  res = httr::POST(url,
                   body = list(IVFPredPID=PID,
                               AutTuneM=AutTuneM,
                               AutTuneN=AutTuneN,
                               RsmpMethod=RsmpMethod,
                               Folds=Folds,
                               Ratio=Ratio,
                               Repeats=Repeats,
                               Learners=Learners),
                   encode = 'json')
  results = unserialize(httr::content(res))
  Path = paste0(OutPath,'/IVFPred')
  dir.create(Path)
  dir.create(paste0(Path,'/acc_to_feature_numbers'))
  dir.create(paste0(Path,'/importance'))

  writexl::write_xlsx(results$eSet$BenchimarkRes, path = paste0(Path,"/benchimark_results_of_all_groups.xlsx"))
  try(for(i in results$eSet$Groups){
    writexl::write_xlsx(results$eSet$importance[[i]],path = paste0(Path,'/importance/group_',i,'.xlsx'))
    writexl::write_xlsx(results$eSet$ACCtoFeatureNum[[i]],path = paste0(Path,'/acc_to_feature_numbers/group_',i,'.xlsx'))
  })
  try(
        writexl::write_xlsx(results$eSet$ImportanceRank,path = paste0(Path,'/importance/importance_rank.xlsx'))
  )
  try(
        writexl::write_xlsx(results$eSet$ImportanceRank[1:10,],path = paste0(Path,'/importance_rank10.xlsx'))
  )
  try(
        writexl::write_xlsx(results$eSet$ACCtoFeatureNumTrend,path = paste0(Path,'/acc_to_feature_numbers_trend.xlsx'))
  )
  try(
        writexl::write_xlsx(results$eSet$CommonFeatures,path = paste0(Path,'/common_features.xlsx'))
  )

  return(results$eSet)
}


#' @title Visualize IVF-ET model results
#' @description VizIVFPred function is mainly aimed to visualize the modeling results calculated by IVFPred function.
#'     It can provide plots with high quality of the final results to make it easier for users to understand.
#' @usage VizIVFPred(PID, OutPath = "default", Brightness = NULL, Palette = NULL)
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark".
#' @param Palette chr. Visualization palette. Available options include options about some journal preference styles
#'     including "cell", "nature", "science", "lancet", "nejm", etc.
#' @return An R6 class object containing the model results
#' @export
#' @examples
#'     res <- InitIVF()
#'    res1 = LoadIVF(PID = res$PID, UseExample = "example#2")
#'    res2 = TransImputIVF(PID=res$PID, Vars="all.x")
#'    res2 = DelLowVarIVF(PID=res$PID)
#'    res2 = DelMissIVF(PID=res$PID)
#'    res2 = TransTypeIVF(PID = res$PID, Vars = "Y,X85,X86,X87,X88,X89,X90,X91,X92,X93,X94,X95,X96,X97,X98",
#'                        To = "factor")
#'    res2 = TransClassIVF(PID = res$PID, Vars = "X47", LevelTo = 4)
#'    res2 = TransScaleIVF(PID = res$PID, Vars = "X55", Method = "normal")
#'    res2 = TransDistrIVF(PID = res$PID, Vars = "X61", Method = "log10")
#'    res3 = IVFPred(PID = res$PID, AutTuneM = "random_search", AutTuneN = 5,
#'                   RsmpMethod = "cv", Folds = 5,
#'                   Learners = "logistic,rf,xgboost")
#'    res3 = VizIVFPred(PID = res$PID, Brightness = "light", Palette = "lancet")
#'    FuncExit(PID = res$PID)
#' @author Weinan Lin, Bin Wang (corresponding author)
VizIVFPred = function(PID,
                      OutPath = "default",
                      Brightness = NULL,
                      Palette = NULL){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  url = paste0(urlhead,'VizIVFPred')

  res = httr::POST(url,
                   body = list(IVFPredPID=PID,
                               Brightness = Brightness,
                               Palette = Palette),
                   encode = 'json')
  results = unserialize(httr::content(res))
  Path = paste0(OutPath,'/VizIVFPred')
  dir.create(Path)
  try(
    ggplot2::ggsave(paste0(Path, "/Benchimark Results of all groups.png"),
                    plot = results$eSet$VizIVFPred[["Plot_Barplot"]],
                    width = 25,
                    height = 15,
                    units = "cm",dpi = 300)
  )
  try(
    ggplot2::ggsave(paste0(Path, "/Trend_of_ACC_to_Feature_Numbers.png"),
                    plot = results$eSet$VizIVFPred[["Plot_Lineplot"]],
                    width = 30,
                    height = 20,
                    units = "cm")
  )
  return(results$eSet)
}


#' @title Validation for IVF-ET data
#' @description Build Vaalidation model for IVF-ET data
#' @usage IVFValid(PID, OutPath = "default", Learner = 'default', VarsNum = 2, AutTuneM = "random_search", AutTuneN = "5", SingleGroup = NULL)
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param Learner chr; learners for build model to validate and explain;
#'     if "default" best model stored in "IVFPred" will be used
#' @param VarsNum num. Number of common features include in all groups;
#' @param AutTuneM chr. Method for hyper-parameter autotuning.
#'     Options include "default", "random_search", "grid_search", "nloptr"(Non-linear optimization), and "gensa"(Generalized simulated annealing).
#'     The "default" option uses the simple training method for parameter optimization of mlr3 package.
#' @param AutTuneN num. Upper limit of model tuning times. It should be more than 20 times to search the appropriate parameters,
#'     but it takes more time. In theory, more time, better training results.
#' @param SingleGroup lgl; Whether only single group is contained
#' @return An R6 class object containing the model results
#' @export
#' @examples
#'     res <- InitIVF()
#'    res1 = LoadIVF(PID = res$PID, UseExample = "example#2")
#'    res2 = TransImputIVF(PID=res$PID, Vars="all.x")
#'    res2 = DelLowVarIVF(PID=res$PID)
#'    res2 = DelMissIVF(PID=res$PID)
#'    res2 = TransTypeIVF(PID = res$PID, Vars = "Y,X85,X86,X87,X88,X89,X90,X91,X92,X93,X94,X95,X96,X97,X98",
#'                        To = "factor")
#'    res2 = TransClassIVF(PID = res$PID, Vars = "X47", LevelTo = 4)
#'    res2 = TransScaleIVF(PID = res$PID, Vars = "X55", Method = "normal")
#'    res2 = TransDistrIVF(PID = res$PID, Vars = "X61", Method = "log10")
#'    res3 = IVFPred(PID = res$PID, AutTuneM = "random_search", AutTuneN = 5,
#'                   RsmpMethod = "cv", Folds = 5,
#'                   Learners = "logistic,rf,xgboost")
#'    res4 = IVFValid(PID = res$PID, VarsNum = 2,SingleGroup = TRUE)
#'    FuncExit(PID = res$PID)
#' @author Weinan Lin, Bin Wang (corresponding author)
IVFValid = function(PID,
                   OutPath = "default",
                   Learner = 'default',
                   VarsNum = 2,
                   AutTuneM = "random_search",
                   AutTuneN = "5",
                   SingleGroup = NULL){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  url = paste0(urlhead,'IVFValid')

  res = httr::POST(url,
                   body = list(IVFPredPID=PID,
                               Learner = Learner,
                               VarsNum = VarsNum,
                               AutTuneM=AutTuneM,
                               AutTuneN=AutTuneN,
                               SingleGroup = SingleGroup
                               ),
                   encode = 'json')
  results = unserialize(httr::content(res))
  Path = paste0(OutPath,'/IVFValid')
  dir.create(Path)
  # dir.create(paste0(Path,'/acc_to_feature_numbers'))
  # dir.create(paste0(Path,'/importance'))
  if(!SingleGroup){
    try(
          writexl::write_xlsx(results$eSet$ValidationRes,path = paste0(Path,"/validation_result.xlsx")))
  }
  return(results$eSet)
}


#' @title Visualize IVF-ET validation results
#' @description VizIVFValid function is mainly aimed to visualize the modeling results calculated by IVFValid function.
#'     It can provide plots with high quality of the final results to make it easier for users to understand.
#' @usage VizIVFValid(PID, OutPath = "default", Brightness = NULL, Palette = NULL)
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark".
#' @param Palette chr. Visualization palette. Available options include options about some journal preference styles
#'     including "cell", "nature", "science", "lancet", "nejm", etc.
#' @return An R6 class object containing the model results
#' @export
#' @examples
#'     res <- InitIVF()
#'    res1 = LoadIVF(PID = res$PID, UseExample = "example#2")
#'    res2 = TransImputIVF(PID=res$PID, Vars="all.x")
#'    res2 = DelLowVarIVF(PID=res$PID)
#'    res2 = DelMissIVF(PID=res$PID)
#'    res2 = TransTypeIVF(PID = res$PID, Vars = "Y,X85,X86,X87,X88,X89,X90,X91,X92,X93,X94,X95,X96,X97,X98",
#'                        To = "factor")
#'    res2 = TransClassIVF(PID = res$PID, Vars = "X47", LevelTo = 4)
#'    res2 = TransScaleIVF(PID = res$PID, Vars = "X55", Method = "normal")
#'    res2 = TransDistrIVF(PID = res$PID, Vars = "X61", Method = "log10")
#'    res3 = IVFPred(PID = res$PID, AutTuneM = "random_search", AutTuneN = 5,
#'                   RsmpMethod = "cv", Folds = 5,
#'                   Learners = "logistic,rf,xgboost")
#'    res4 = IVFValid(PID = res$PID, SingleGroup = TRUE)
#'    res4 = VizIVFValid(PID = res$PID, Brightness = "dark", Palette = "lancet")
#'    FuncExit(PID = res$PID)
#' @author Weinan Lin, Bin Wang (corresponding author)
VizIVFValid = function(PID,
                      OutPath = "default",
                      Brightness = NULL,
                      Palette = NULL){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  url = paste0(urlhead,'VizIVFValid')

  res = httr::POST(url,
                   body = list(IVFPredPID=PID,
                               Brightness = Brightness,
                               Palette = Palette),
                   encode = 'json')
  results = unserialize(httr::content(res))
  Path = paste0(OutPath,'/VizIVFValid')
  dir.create(Path)
  dir.create(paste0(Path,'/Partial dependence'))
  if(!results$eSet$SingleGroup){
    try(
      ggplot2::ggsave(paste0(Path,"/Validation result.png"),
                      plot =  results$eSet$VizIVFValid[["Plot_Barplot"]],
                      width = 25,
                      height = 15,
                      units = "cm",dpi = 300)
    )
  }

  for(i in results$eSet$Explain[['VarsExplain']]){
    try(
      ggplot2::ggsave(filename = paste0(Path,'/Partial dependence/Y_',i,'.png'),
                      results$eSet$CPP_Plot[[i]],
                      width = 6,
                      height = 6)
    )
  }

  return(results$eSet)
}


#' @title End the module analysis
#' @description End the module analysis
#' @usage FuncExit(PID)
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions.
#' @details
#' @return
#' @export
#' @examples
#'    res <- InitIVF()
#'    res1 = LoadIVF(PID = res$PID, UseExample = "example#1")
#'    FuncExit(PID = res$PID)
#' @author Weinan Lin, Bin Wang (corresponding author)

FuncExit = function(PID){
  url = paste0(urlhead,'Exit')
  res = httr::POST(url,
                   body = list(PID=PID),
                   encode = 'json')
  if(res$status_code == 200){
    return("Success to exit. Thanks for using ExposomeX platform!")
  }else{
    return("No process needs exit. Thanks for using ExposomeX platform!")
  }
}





